In [103]:
import numpy as np
import re

In [104]:
with open("../data/sample_text.txt", "r") as file:
    text = file.read()

In [105]:
def text_preprocessing(text):
  # Loại bỏ kí tự đặc biệt thay thế bằng khoảng trắng
  text = re.sub(r'[^\w\s]', ' ', text)

  # Xóa khoảng trắng đầu câu và cuối câu
  text = re.sub(r'^\s+|\s+$', '', text)

  # Thay thế tất cả các khoảng trắng liên tiếp bằng một khoảng trắng duy nhất.
  text = re.sub(r'\s+', ' ', text, flags=re.I)
  # Chuyển đổi tất cả các ký tự trong câu thành chữ thường.
  text = text.lower()

  return text

In [106]:
text = text_preprocessing(text)
text = text.split()

In [107]:
print(text[:5])

['the', 'great', 'barrier', 'reef', 'is']


In [108]:
def to_bag(corpus):
  bag_set = set(corpus)
  return bag_tuple

In [109]:
def words_to_bag(corpus, bag):
  bag_arr = list(bag)
  words_to_bag = np.zeros(len(bag_arr))
  
  text = text_preprocessing(corpus)
  text = text.split()
  
  for word in text:
    if word in bag_arr:
      index = bag_arr.index(word)
      words_to_bag[index] += 1
    else:
      return ("words_not_in_corpus")
      
  return words_to_bag

In [110]:
test = ['test', 'thoi', 'lam', 'gi', 'cang']

words_to_bag("test thoi lam", test)

array([1., 1., 1., 0., 0.])

In [111]:
words_to_bag("gi cang gi cang gi cang gi cang cang", test)

array([0., 0., 0., 4., 5.])

In [112]:
from sklearn.feature_extraction.text import CountVectorizer

document = ["test thoi lam gi cang"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(document)

vector = vectorizer.transform(["gi cang gi cang gi cang gi cang cang"])
print(vector.toarray())

[[5 4 0 0 0]]
